[package]
name = "calendarcord"
version = "0.1.0"
authors = ["Alex P. <alexeek@protonmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
serenity = { git = "https://github.com/acdenisSK/serenity", branch = "await_next" }